export const MENU_ITEMS = [
  {
    name: "For jobseekers",
    link: "#",
    subItems: [
      { name: "Resume tips", link: "#" },
      { name: "Job interview advice", link: "#" },
      { name: "Career coaching", link: "#" },
    ],
  },
  {
    name: "For clients",
    link: "#",
    subItems: [
      { name: "Post a job", link: "#" },
      { name: "View applicants", link: "#" },
      { name: "Client testimonials", link: "#" },
      { name: "Recruitment services", link: "#" },
    ],
  },
  {
    name: "Sectors",
    link: "#",
    subItems: [
      { name: "IT & Software", link: "#" },
      { name: "Marketing & Sales", link: "#" },
      { name: "Engineering", link: "#" },
    ],
  },
  {
    name: "Resources",
    link: "#",
    subItems: [
      { name: "Blog", link: "#" },
      { name: "E-books", link: "#" },
      { name: "Webinars", link: "#" },
      { name: "Case studies", link: "#" },
    ],
  },
];

export const JOBS = [
  {
    technology: "React.js",
    title: "Frontend Developer",
    location: "London",
    salary: "£65,000",
    description: "Develop responsive UIs using React and TypeScript.",
    date: "02/04/2025",
  },
  {
    technology: "Node.js",
    title: "Backend Engineer",
    location: "Manchester",
    salary: "£70,000",
    description: "Build scalable APIs and services using Node.js and Express.",
    date: "03/04/2025",
  },
  {
    technology: "Python",
    title: "Data Analyst",
    location: "Birmingham",
    salary: "£55,000",
    description: "Analyze business data and build insightful dashboards.",
    date: "04/04/2025",
  },
  {
    technology: "Java",
    title: "Software Engineer",
    location: "Leeds",
    salary: "£68,000",
    description: "Work on backend services using Java and Spring Boot.",
    date: "05/04/2025",
  },
  {
    technology: "AWS",
    title: "Cloud Architect",
    location: "Bristol",
    salary: "£90,000",
    description: "Design and maintain secure AWS cloud infrastructure.",
    date: "06/04/2025",
  },
  {
    technology: "Angular",
    title: "Frontend Developer",
    location: "Liverpool",
    salary: "£62,000",
    description: "Create scalable UI solutions using Angular and TypeScript.",
    date: "07/04/2025",
  },
  {
    technology: "DevOps",
    title: "DevOps Engineer",
    location: "Sheffield",
    salary: "£75,000",
    description: "Implement CI/CD pipelines and monitor production systems.",
    date: "08/04/2025",
  },
  {
    technology: "SQL",
    title: "Database Administrator",
    location: "Nottingham",
    salary: "£58,000",
    description: "Maintain and tune PostgreSQL and SQL Server databases.",
    date: "09/04/2025",
  },
  {
    technology: "Flutter",
    title: "Mobile Developer",
    location: "Glasgow",
    salary: "£60,000",
    description: "Develop and maintain mobile apps with Flutter and Dart.",
    date: "10/04/2025",
  },
];
