import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/next";
import { Roboto } from "next/font/google";
import "@/styles/globals.css";
import "keen-slider/keen-slider.min.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import BootstrapClient from "@/components/BootstrapClient";
import Navbar from "@/components/Navbar";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Recruitment Site Application</title>
        <meta name="description" content="A better way to recruit." />
        <link rel="icon" href="/icon.ico" />
        <link rel="stylesheet" href="/styles/custom.css" />
      </head>
      <body className={`${roboto.variable} antialiased`}>
        <Navbar />
        {children}
        <BootstrapClient />
        <Analytics />
      </body>
    </html>
  );
}
